# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import edon_v2_pb2 as edon__v2__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in edon_v2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EdonV2ServiceStub(object):
    """EdonV2Service - EDON CAV Engine gRPC Service (v2)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/edon.v2.EdonV2Service/Health',
                request_serializer=edon__v2__pb2.HealthRequest.SerializeToString,
                response_deserializer=edon__v2__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ComputeCavBatchV2 = channel.unary_unary(
                '/edon.v2.EdonV2Service/ComputeCavBatchV2',
                request_serializer=edon__v2__pb2.CavBatchV2Request.SerializeToString,
                response_deserializer=edon__v2__pb2.CavBatchV2Response.FromString,
                _registered_method=True)
        self.StreamCavWindowsV2 = channel.stream_stream(
                '/edon.v2.EdonV2Service/StreamCavWindowsV2',
                request_serializer=edon__v2__pb2.CavWindowV2.SerializeToString,
                response_deserializer=edon__v2__pb2.CavStreamResponse.FromString,
                _registered_method=True)


class EdonV2ServiceServicer(object):
    """EdonV2Service - EDON CAV Engine gRPC Service (v2)
    """

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeCavBatchV2(self, request, context):
        """Batch computation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCavWindowsV2(self, request_iterator, context):
        """Bidirectional streaming: client sends windows, server responds with results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdonV2ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=edon__v2__pb2.HealthRequest.FromString,
                    response_serializer=edon__v2__pb2.HealthResponse.SerializeToString,
            ),
            'ComputeCavBatchV2': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeCavBatchV2,
                    request_deserializer=edon__v2__pb2.CavBatchV2Request.FromString,
                    response_serializer=edon__v2__pb2.CavBatchV2Response.SerializeToString,
            ),
            'StreamCavWindowsV2': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamCavWindowsV2,
                    request_deserializer=edon__v2__pb2.CavWindowV2.FromString,
                    response_serializer=edon__v2__pb2.CavStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'edon.v2.EdonV2Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('edon.v2.EdonV2Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EdonV2Service(object):
    """EdonV2Service - EDON CAV Engine gRPC Service (v2)
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edon.v2.EdonV2Service/Health',
            edon__v2__pb2.HealthRequest.SerializeToString,
            edon__v2__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeCavBatchV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/edon.v2.EdonV2Service/ComputeCavBatchV2',
            edon__v2__pb2.CavBatchV2Request.SerializeToString,
            edon__v2__pb2.CavBatchV2Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCavWindowsV2(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/edon.v2.EdonV2Service/StreamCavWindowsV2',
            edon__v2__pb2.CavWindowV2.SerializeToString,
            edon__v2__pb2.CavStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
