# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: edon.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'edon.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nedon.proto\x12\x04\x65\x64on\"\xc0\x01\n\x11StreamDataRequest\x12\x0b\n\x03\x65\x64\x61\x18\x01 \x03(\x02\x12\x0c\n\x04temp\x18\x02 \x03(\x02\x12\x0b\n\x03\x62vp\x18\x03 \x03(\x02\x12\r\n\x05\x61\x63\x63_x\x18\x04 \x03(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x05 \x03(\x02\x12\r\n\x05\x61\x63\x63_z\x18\x06 \x03(\x02\x12\x0e\n\x06temp_c\x18\x07 \x01(\x02\x12\x10\n\x08humidity\x18\x08 \x01(\x02\x12\x0b\n\x03\x61qi\x18\t \x01(\x05\x12\x12\n\nlocal_hour\x18\n \x01(\x05\x12\x13\n\x0bstream_mode\x18\x0b \x01(\x08\"\xac\x01\n\x13StreamStateResponse\x12\x0f\n\x07\x63\x61v_raw\x18\x01 \x01(\x05\x12\x12\n\ncav_smooth\x18\x02 \x01(\x05\x12\r\n\x05state\x18\x03 \x01(\t\x12$\n\x05parts\x18\x04 \x01(\x0b\x32\x15.edon.ComponentScores\x12%\n\x08\x63ontrols\x18\x05 \x01(\x0b\x32\x13.edon.ControlScales\x12\x14\n\x0ctimestamp_ms\x18\x06 \x01(\x03\"P\n\x0f\x43omponentScores\x12\x0b\n\x03\x62io\x18\x01 \x01(\x02\x12\x0b\n\x03\x65nv\x18\x02 \x01(\x02\x12\x11\n\tcircadian\x18\x03 \x01(\x02\x12\x10\n\x08p_stress\x18\x04 \x01(\x02\">\n\rControlScales\x12\r\n\x05speed\x18\x01 \x01(\x02\x12\x0e\n\x06torque\x18\x02 \x01(\x02\x12\x0e\n\x06safety\x18\x03 \x01(\x02\x32\x92\x01\n\x0b\x45\x64onService\x12>\n\x08GetState\x12\x17.edon.StreamDataRequest\x1a\x19.edon.StreamStateResponse\x12\x43\n\x0bStreamState\x12\x17.edon.StreamDataRequest\x1a\x19.edon.StreamStateResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'edon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMDATAREQUEST']._serialized_start=21
  _globals['_STREAMDATAREQUEST']._serialized_end=213
  _globals['_STREAMSTATERESPONSE']._serialized_start=216
  _globals['_STREAMSTATERESPONSE']._serialized_end=388
  _globals['_COMPONENTSCORES']._serialized_start=390
  _globals['_COMPONENTSCORES']._serialized_end=470
  _globals['_CONTROLSCALES']._serialized_start=472
  _globals['_CONTROLSCALES']._serialized_end=534
  _globals['_EDONSERVICE']._serialized_start=537
  _globals['_EDONSERVICE']._serialized_end=683
# @@protoc_insertion_point(module_scope)
